web-blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :comments
  resources :users
  resources :posts
  resources :categories

end

web-blog/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Blog-CD</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->

    <ul class="nav navbar-nav navbar-right">
      <li><%=link_to "Posts", posts_path%></li>
      <li><%=link_to "Usuários", users_path%></li>
      <li><%=link_to "Categorias", categories_path%></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "#{current_user.name}", edit_user_path(current_user)%></li>
          <li role="separator" class="divider"></li>
          <li><%=link_to "Sair", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

web-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= render 'layouts/menu' %>
<% end %>

<div class="container">
  <%= yield %>
<div>

</body>
</html>